name: RyuPvPMod
main: me.hawkeyeshi.RyuPvPMod.RyuPvPMod
version: 1.0

commands: 
   RyuInfo:
     description: Information about the RyuPvPMod plugin
     usage: /RyuInfo
   cheater:
     description: Ban a cheater!
     usage: /cheater [player]
     permission: RyuPvPMod.cheater
       default: OP
   badboy:
     description: Deem someone a bad boy!
     usage: /badboy [user]
     permission: RyuPvPMod.badboy
       default: OP

   boomdoom:
     description: Doom someone!
     usage: /boomdoom [player]
     permission: RyuPvPMod.boomdoom
       default: OP
  wazzup:
    description: What's Up? >:3
      usage: /wazzup
  hawk:
    description: See if someone can fly :D
    usage: /hawk [player]
    permission: RyuPvPMod.hawk
      default: OP
  requiem:
    description: A secwet command for RequiemDestiny only.
    usage: /requiem [player]
    permission: RyuPvPMod.requiem
      default: OP
  ryusay:
    description: A broadcasting command!
    usage: /ryusay [message]
    permission: RyuPvPMod.ryusay
      default: OP
